
<MainWid>
    canvas:
        Color:
            rgb: 1, 1, 1
        Rectangle:
            pos: self.pos
            size: self.size

<StartWid>
    orientation: 'vertical'
    canvas:
        Color:
            rgb: 0.3, 0.3, 0.9
        Rectangle:
            pos: self.pos
            size: self.size
    BoxLayout:
        size_hint_y: 0.45
    ToggleButton:
        text: 'Create/Enter Database'
        size_hint_y: 0.1
        on_press: root.create_database()
    BoxLayout:
        size_hint_y: 0.45
        
<DataBaseWid>
    orientation: 'vertical'
    canvas:
        Color:
            rgb: 0.3, 0.3, 0.9
        Rectangle:
            pos: self.pos
            size: self.size
    ScrollView:
        size: self.size
        GridLayout:
            id: container
            padding: [10, 10, 10, 10]
            spacing: 5
            size_hint_y: None
            cols: 1
            row_default_height: root.height * 0.2
            height: self.minimum_height

<NewDataButton>
    font_size: self.height * 0.5
    text: '+'
    on_press: root.create_new_product()

<LeftLabel@Label>:
    text_size: self.size
    halign: 'left'

<InsertDataWid>
    orientation: 'vertical'
    canvas:
        Color:
            rgb: 0.3, 0.3, 0.9
        Rectangle:
            pos: self.pos
            size: self.size

    LeftLabel:
        text: 'Name'
    TextInput:
        id: ti_name
        hint_text: 'Enter product name'

    LeftLabel:
        text: 'Code'
    TextInput:
        id: ti_code
        hint_text: 'Enter code'

    LeftLabel:
        text: 'Price'
    TextInput:
        id: ti_price
        hint_text: 'Enter price'

    LeftLabel:
        text: 'Quantity'
    TextInput:
        id: ti_quantity
        hint_text: 'Enter quantity'

    BoxLayout:
        size_hint_y: 5

    BoxLayout:
        Button:
            text: 'Create'
            on_press: root.insert_data()
        Button:
            text: 'Exit'
            on_press: root.back_to_dbw()

<MessagePopup>
    BoxLayout:
        orientation: 'vertical'
        Label:
            id: message
            size_hint: 1, 0.8
        Button:
            size_hint: 1, 0.2
            text:'Back'
            on_press: root.dismiss()

<DataWid>
    data: ''
    data_id: ''
    canvas:
        Color:
            rgb: 0.3, 0.3, 0.9
        Rectangle:
            pos: self.pos
            size: self.size
    Label:
        text: root.data
        size_font: self.width * 0.4
        size_hint_x: 0.9
    Button:
        size_hint_x: 0.1
        text: 'Edit'
        on_press: root.update_data(root.data_id)
        


















            